print("Loading...")
import os
from pathlib import Path
import torch
from datasets import Dataset
from transformers import (
    AutoTokenizer,
    DataCollatorForLanguageModeling,
    TrainingArguments
)
from unsloth import FastLanguageModel
from trl import SFTConfig,SFTTrainer

os.environ["TOKENIZERS_PARALLELISM"] = "false"

class TrainConfig:
    model_name: str = "model"
    inputs_folder: str = "/root/educational-AI-agent/data/model_0/inputs"
    outputs_folder: str = "/root/educational-AI-agent/data/model_0/outputs"
    output_dir: str = "./lora_model"

    batch_size: int = 2
    lr: float = 2e-4
    epochs: int = 5
    max_length: int = 1024 * 10

    lora_r: int = 16
    lora_alpha: int = 16
    lora_dropout: float = 0.0

    logging_steps: int = 10


train_prompt_style = """You are given an XML file that represents an asciinema terminal session. The XML file contains a root <recording> tag and several child tags, each representing an event. These child tags can be either <user_input> (representing user commands) or <system_output> (representing system responses). Each tag includes a timestamp id (in seconds) that indicates when the event occurred.

Your task is to output a numbered file from processing the XML file and group the sequential events so that each group represents a single high-level goal. The groups should contain one or more consecutive events (both <user_input> and <system_output>) that together form a logical unit of work. At the end of each grouping, you must output a "0" on a new line as a separator, and the entire file must end with a "0".

**Important Notes:**
1. **End-of-Group Separator:** After each group of events corresponding to a high-level goal, output a single "0" on a new line. Also, ensure that the overall output ends with a "0".
2. **Keystroke-level Input:** The parsed XML file is generated by recording every keystroke. This means that a complete command may be split across multiple consecutive <user_input> tags. Your grouping should take this into account and combine these keystroke events into a single logical command or goal.

Input:
An XML file formatted as follows (the line number corresponds to the order of events):

Example snippet (note that user input events may represent only a single keystroke):

  <system_output timestamp="0.096022">[?2004h]0;demo@boxtop: ~demo@boxtop:~$ </system_output>
  <user_input timestamp="9.163614">s</user_input>
  <system_output timestamp="9.164051">s</system_output>
  <user_input timestamp="9.365744">s</user_input>
  <system_output timestamp="9.366263">s</system_output>
  <user_input timestamp="9.589844">h</user_input>
  <system_output timestamp="9.59026">h</system_output>
  <user_input timestamp="9.708352"> </user_input>
  <system_output timestamp="9.708844"> </system_output>
  <user_input timestamp="10.1118">1</user_input>
  <system_output timestamp="10.112236">1</system_output>
  <user_input timestamp="10.270878">0</user_input>
  <system_output timestamp="10.271223">0</system_output>
  <user_input timestamp="10.471565">.</user_input>
  <system_output timestamp="10.471898">.</system_output>
  <user_input timestamp="10.594981">0</user_input>
  <system_output timestamp="10.595383">0</system_output>
  <user_input timestamp="10.757499">.</user_input>
  <system_output timestamp="10.757882">.</system_output>
  <user_input timestamp="11.140897">7</user_input>
  <system_output timestamp="11.14119">7</system_output>
  <user_input timestamp="11.603706">.</user_input>
  <system_output timestamp="11.604019">.</system_output>
  <user_input timestamp="12.330584">1</user_input>
  <system_output timestamp="12.331455">1</system_output>
  <user_input timestamp="12.632256">3</user_input>
  <system_output timestamp="12.633323">3</system_output>
  <user_input timestamp="13.446626">8</user_input>
  <system_output timestamp="13.447562">8</system_output>
  <user_input timestamp="14.510021"> (End of input marker or newline)</user_input>

Assume that each tag is assigned a line number based on its position in the XML file (i.e. line 1 for the first event, line 2 for the second, and so on).

Expected Output Format:
For each group of events that collectively accomplish a high-level goal, output the corresponding line numbers in sequential order (each on a new line). At the end of each group, output a single "0" on a new line to mark the end of that grouping. The entire output must also end with a "0".

For example, if the first high-level goal is accomplished by events on lines 1 through 3, and the next goal is accomplished by events on lines 4 through 8, you will output:
1
2
3
0
4
5
6
7
8
0

Task Summary:
1. Parse the XML file.
2. Group the events (<user_input> and <system_output>) into sequential blocks, where each block represents a complete high-level goal.
    - Remember that <user_input> events may be recorded for each keystroke. Therefore, consecutive keystroke events that form a complete command should be grouped together.
3. Output the line numbers of each event in each group, printing "0" on a new line after each group.
4. Ensure that the overall output ends with a "0".

Example:
Given an XML file with the following events and assuming a logical grouping is determined as follows:

- **Group 1:** Events 1–3 (e.g., initial terminal prompt or command display).
- **Group 2:** Events 4–8 (e.g., a command input that spans multiple keystroke events and its associated outputs).

Then your output should be:
1
2
3
0
4
5
6
7
8
0

Additional Notes:
- The grouping must be sequential; no events should be skipped.
- All events in a group must be consecutive in the XML file.
- Use the provided dataset with correct input and corresponding grouping output examples to learn the grouping patterns.
- The model should intelligently group keystroke-level <user_input> events that together form a complete command.

### XML Input:
{}

### Output:
{}"""


def get_base_filename(filepath):
    return os.path.basename(filepath).split('.')[0]

def load_paired_data(inputs_dir, outputs_dir):
    """
    Loads and pairs data by matching basenames from separate input and output folders.
    """
    print(f"Looking for inputs in: {inputs_dir}")
    print(f"Looking for outputs in: {outputs_dir}")

    # Create a map of {basename: full_path} for all files in the outputs directory
    response_map = {get_base_filename(f): os.path.join(outputs_dir, f) for f in os.listdir(outputs_dir)}

    paired_inputs = []
    paired_responses = []

    # Iterate through the inputs directory to find matches
    for filename in os.listdir(inputs_dir):
        base_name = get_base_filename(filename)
        
        # If a matching basename is found in the response map, pair them
        if base_name in response_map:
            input_path = os.path.join(inputs_dir, filename)
            response_path = response_map[base_name]
            
            print(f"✅ Matched: {filename} -> {os.path.basename(response_path)}")
            
            with open(input_path, 'r', encoding='utf-8') as f_in:
                paired_inputs.append(f_in.read())
            with open(response_path, 'r', encoding='utf-8') as f_out:
                paired_responses.append(f_out.read())
        else:
            print(f"⚠️ Warning: No matching output found for input file: {filename}")
            
    return paired_inputs, paired_responses

def main():
    config = TrainConfig()

    model, tokenizer = FastLanguageModel.from_pretrained(
        model_name = config.model_name,
        max_seq_length = config.max_length,
        dtype = None,
        load_in_4bit = True,
    )


    if tokenizer.pad_token is None:
        tokenizer.pad_token = tokenizer.eos_token

    # Apply LoRA
    model_lora = FastLanguageModel.get_peft_model(
        model,
        r=16,
        target_modules = ["q_proj", "k_proj", "v_proj", "o_proj",
                    "gate_proj", "up_proj", "down_proj"],
        lora_alpha=16,
        lora_dropout=0,
        bias="none",
        use_gradient_checkpointing="unsloth",
        random_state=3407,
        use_rslora=False,
        loftq_config=None,
    )
    # Prepare dataset
    inputs, responses = load_paired_data(config.inputs_folder, config.outputs_folder)
    EOS_TOKEN = tokenizer.eos_token
    def formatting_prompts_func(examples):
        texts = []
        for inp, out in zip(examples["Input"], examples["Response"]):
            texts.append(train_prompt_style.format(inp, out) + EOS_TOKEN)
        return {"text": texts}

    raw_ds = Dataset.from_dict({"Input": inputs, "Response": responses})
    formatted_ds = raw_ds.map(formatting_prompts_func, batched = True,)

    trainer = SFTTrainer(
        model = model_lora,
        train_dataset = formatted_ds,
        dataset_text_field = "text",
        max_seq_length = config.max_length,
        tokenizer = tokenizer,
        args = TrainingArguments(
            per_device_train_batch_size = config.batch_size,
            gradient_accumulation_steps = 1,
            num_train_epochs = config.epochs,
            warmup_steps = 5,
            learning_rate = config.lr,
            fp16 = not torch.cuda.is_bf16_supported(),
            bf16 = torch.cuda.is_bf16_supported(),
            logging_steps = config.logging_steps,
            optim = "adamw_8bit",
            weight_decay = 0.01,
            lr_scheduler_type = "linear",
            seed = 3407,
            output_dir = config.output_dir,
            report_to = "none",
        ),
    )

    # Train
    trainer.train()

    # Merge adapters and save full model as GGUF
    output_gguf_path = os.path.join(config.output_dir, "model.gguf")
    model.save_pretrained_gguf(output_gguf_path, tokenizer)
    print(f"Merged full model saved in GGUF format at {config.output_dir}/model.gguf")



if __name__ == '__main__':
    main()
